runtime: python39  # or the correct runtime version you are using
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  MYSQL_HOST: "makeiteasy.ck0scewemjwp.us-east-1.rds.amazonaws.com"
  MYSQL_USER: "xz3052"
  MYSQL_PASSWORD: "dbuserdbuser"
  MYSQL_DB: "Order_Service"